version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: ../Dockerfile
      target: build
    volumes:
      - ..:/workspace:cached
      - ${HOME}${USERPROFILE}/.nuget/packages:/home/vscode/.nuget/packages:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
